"use client";
import React, { useState, useMemo, Dispatch, SetStateAction } from "react";
import { Card } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Star, Search } from "lucide-react";

type Route = (typeof routes)[number];
type Filters = {
  search: string;
  scenery: number;
  difficulty: number;
  days: number;
  backpack: string;
};

const routes = [
  {
    id: 1,
    name: "武功山",
    province: "江西省",
    city: "萍乡市",
    district: "",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description: "东部经典线路。奇峰、飞瀑、怪松、云海",
    altitude: 1918.3,
  },
  {
    id: 2,
    name: "庐山",
    province: "江西省",
    city: "九江市",
    district: "",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description: "东部经典线路。五老峰日出：绝美壮阔",
    altitude: 1474.0,
  },
  {
    id: 3,
    name: "九华山",
    province: "安徽省",
    city: "池州市",
    district: "青阳县",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description: "东部经典线路。野路较多，荆棘、小竹林较多",
    altitude: 1342.0,
  },
  {
    id: 4,
    name: "三清山",
    province: "江西省",
    city: "上饶市",
    district: "玉山县",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description:
      "东部经典线路。奇崛秀美。玉京峰为最高，海拔1819.9米，是江西第五高峰和怀玉山脉的最高峰。",
    altitude: 1819.9,
  },
  {
    id: 5,
    name: "牯牛降",
    province: "安徽省",
    city: "黄山市",
    district: "祁门县",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description:
      "东部经典线路。牯牛降以雄、奇、险著称，是黄山山脉向西延伸的主体，古称“西黄山”，山岳风光秀美绮丽。",
    altitude: 1727.6,
  },
  {
    id: 6,
    name: "千八（黄茅尖）",
    province: "浙江省",
    city: "丽水市",
    district: "龙泉市",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description:
      "华东第一虐。龙泉市、洞宫山脉最高峰、浙江省最高峰。大环线85公里。传统线47公里。",
    altitude: 1929.0,
  },
  {
    id: 7,
    name: "华东K2",
    province: "江西省",
    city: "上饶市",
    district: "铅山县",
    overall: 5,
    scenery: 5,
    difficulty: 5,
    days: 2,
    backpack: "重装",
    description:
      "华东虐西线。从江西独竖尖穿越到福建省第二高峰香炉峰的徒步路线。长达30多公里。日夜温差大，上下落差大，山脊线绵长起伏，很有挑战性，兼具沟谷、深涧、乱石坡、草甸、石岭、丛林等多重地貌。山高林密、路途艰险，人迹罕至。",
    altitude: 2128.0,
  },
  {
    id: 8,
    name: "清凉峰",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 5,
    scenery: 5,
    difficulty: 2,
    days: 2,
    backpack: "重装",
    description:
      "东部经典线路临。安与绩溪歙县界山、天目山脉最高峰、杭州市最高峰；可单走南线或分两日走北线，轻装，1天可轻装环线",
    altitude: 1787.4,
  },
  {
    id: 9,
    name: "七尖（大仙顶）",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 5,
    scenery: 5,
    difficulty: 5,
    days: 2,
    backpack: "重装",
    description:
      "经典虐线45公里。七尖（仙人顶、龙王山、药王峰、千亩田、桐杭岗、仰天坪、大仙顶）  天目山脉之东天目山主峰",
    altitude: 1479.7,
  },
  {
    id: 10,
    name: "神农架",
    province: "湖北省",
    city: "十堰市",
    district: "",
    overall: 5,
    scenery: 5,
    difficulty: 5,
    days: 3,
    backpack: "重装",
    description:
      "老君山线路:木鱼——彩旗村——谭家坪——花岩窝——杜鹃林（营地）——城墙岩——老君山——黄昏岭——老君寨——野猪林——原始森林——马家湾（营地）——蚂蝗沟——叶家垭——彩旗村——木鱼。",
    altitude: 2936.0,
  },
  {
    id: 11,
    name: "楠溪江溯源",
    province: "浙江省",
    city: "温州市",
    district: "永嘉县",
    overall: 5,
    scenery: 4,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description: "溯溪经典线路:水秀、岩奇、瀑多、村古、滩美、林幽。",
    altitude: 1270.0,
  },
  {
    id: 12,
    name: "昱岭四尖",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 5,
    scenery: 4,
    difficulty: 5,
    days: 2,
    backpack: "重装",
    description:
      "虐线:大明山后山下山需要攀爬，注意安全。浩川村→福泉村→光明顶搁船尖（海拔1481米）→丹阳岗→雨伞尖（1459.8）→大岭塔（1446.5）→岭后山（1446）→大明山千亩田营地（1150）→牵牛岗雷达站（1489.8）→大明山→大明山村。全程35公里",
    altitude: 1481.0,
  },
  {
    id: 13,
    name: "三尖（花岩石）",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 5,
    scenery: 4,
    difficulty: 5,
    days: 2,
    backpack: "重装",
    description:
      "虐线，临安三尖线路最高峰。太子尖(海拔1558米)、百丈岭(1334米)、童公尖(1558米)，全程路线 因都在山脊上走，视野开阔，山两边景色尽收眼底，如果运气好还可以看到云海云瀑。其中百丈岭小环线雪景推荐。",
    altitude: 1598.0,
  },
  {
    id: 14,
    name: "公孟",
    province: "浙江省",
    city: "台州市",
    district: "仙居县",
    overall: 5,
    scenery: 4,
    difficulty: 3,
    days: 2,
    backpack: "重装",
    description:
      "风景优美，新手友好线可选择轻装两日，宿公盂（上平/下平村），公盂背海拔1300米。",
    altitude: 1300.0,
  },
  {
    id: 15,
    name: "缙云12峰",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 5,
    scenery: 4,
    difficulty: 5,
    days: 2,
    backpack: "重装",
    description:
      "虐线：起点为溶江乡岩门村，途经雅江，山坑，古方天桥，古方山水库，古方山尖（1216.8米）、青峰岗（1248米），     抱骨岭头，水库边营地，灵江源头石碑，双岩尖（1345米）、风动岩、麦磨岩（1374米）、仰天堂凹高山营地、仰天堂尖（1358米），红桃岭凉亭、仙桶尖（1268.4米）、陈大寮山尖（1269米）、马少岭岗（1284米）、水家样、南溪尖（1231米）、东余村、天堂尖（1184米）、新路林场、水湖岗（1140米）、四方岩（1117米）。终点为大洋镇新西寮村黄寮自然村，全程63公里左右。",
    altitude: 1358.0,
  },
  {
    id: 16,
    name: "黄山野路",
    province: "安徽省",
    city: "黄山市",
    district: "",
    overall: 5,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "世界遗产。",
    altitude: 1864.8,
  },
  {
    id: 17,
    name: "钱江源穿越",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "重装",
    description:
      "钱江源风地处浙，皖，赣三省交界的开化县北部，有“浙西兴安岭”之称。路线：从古田山风景区出发——途径江西东头村——长虹河滩村——长虹库坑村——长虹西坑村——何田乡方心村——江西栗木坦——最后到达钱江源国家森林公园，全程约35公里。",
    altitude: 1145.0,
  },
  {
    id: 18,
    name: "十连坑",
    province: "浙江省",
    city: "宁波市",
    district: "鄞州区",
    overall: 4,
    scenery: 4,
    difficulty: 5,
    days: 2,
    backpack: "重装",
    description:
      "虐线：十连坑的山海拔不高，最高峰883m.但是路难找，蚊虫多，攀爬多，总爬升近3000m。",
    altitude: 883.0,
  },
  {
    id: 19,
    name: "五府岗穿越",
    province: "江西省",
    city: "上饶市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "重装",
    description: "26公里。五府岗主峰1910米。  以云海、日出、日落、奇石而著称。",
    altitude: 1891.6,
  },
  {
    id: 20,
    name: "黄岗山（黄冈山）",
    province: "福建省",
    city: "南平市",
    district: "武夷山市",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "重装",
    description: "42公里。黄冈山雄踞东南之巅，江西省第一高峰。",
    altitude: 2160.0,
  },
  {
    id: 21,
    name: "军峰山",
    province: "江西省",
    city: "抚州市",
    district: "南丰县",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "重装",
    description: "抚州第一高峰",
    altitude: 1761.0,
  },
  {
    id: 22,
    name: "汤公山道场坪铁匠山吴越古道浙西天池",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "重装",
    description: "可连起来重装，也可单独成1日线。乐利峰海拔1300。雪景很美。",
    altitude: 1300.0,
  },
  {
    id: 23,
    name: "金紫尖",
    province: "浙江省",
    city: "杭州市",
    district: "淳安县",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "重装",
    description: "昱岭山脉主峰",
    altitude: 1450.8,
  },
  {
    id: 24,
    name: "四岙(四明山→里岙)",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 4,
    days: 2,
    backpack: "轻装",
    description: "48km。",
    altitude: 1018.0,
  },
  {
    id: 25,
    name: "大洋山",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "16公里。括苍山脉最高峰、缙云最高峰。",
    altitude: 1500.6,
  },
  {
    id: 26,
    name: "东白山",
    province: "浙江省",
    city: "金华市",
    district: "东阳市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "会稽山脉最高峰。高山草甸、风车云海、蓝天白云。13公里",
    altitude: 1194.6,
  },
  {
    id: 27,
    name: "古方山",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "括苍山脉主峰。",
    altitude: 1217.0,
  },
  {
    id: 28,
    name: "黑龙潭",
    province: "浙江省",
    city: "宁波市",
    district: "余姚市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "溯溪。",
    altitude: null,
  },
  {
    id: 29,
    name: "九龙山",
    province: "浙江省",
    city: "丽水市",
    district: "遂昌县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "仙霞岭山脉最高峰、遂昌县最高峰。",
    altitude: 1724.2,
  },
  {
    id: 30,
    name: "龙王山（七尖）",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "安吉县、天目山脉主峰、湖州市最高峰。冬天雾凇、雪景推荐。",
    altitude: 1587.4,
  },
  {
    id: 31,
    name: "龙须山七姑山连穿",
    province: "安徽省",
    city: "宣城市",
    district: "绩溪县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "龙须山脊是风化的岩石沙砾,",
    altitude: 1048.6,
  },
  {
    id: 32,
    name: "炉西峡",
    province: "浙江省",
    city: "丽水市",
    district: "景宁县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "经典溯溪线路",
    altitude: null,
  },
  {
    id: 33,
    name: "披云山",
    province: "浙江省",
    city: "丽水市",
    district: "龙泉市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "仙霞岭山脉次高峰、又名天师山",
    altitude: 1680.0,
  },
  {
    id: 34,
    name: "千岛湖",
    province: "浙江省",
    city: "杭州市",
    district: "淳安县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "自驾线路。可结合金紫尖环线",
    altitude: null,
  },
  {
    id: 35,
    name: "灵山",
    province: "江西省",
    city: "上饶市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "奇石。",
    altitude: 1496.0,
  },
  {
    id: 36,
    name: "武夷山",
    province: "福建省",
    city: "南平市",
    district: "武夷山市",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "世界自然遗产。",
    altitude: 2158.0,
  },
  {
    id: 37,
    name: "白鹤尖（云和梯田）",
    province: "浙江省",
    city: "丽水市",
    district: "云和县",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "云和县、洞宫山脉主峰、云和县最高峰。",
    altitude: 1593.1,
  },
  {
    id: 38,
    name: "豺狗狼尖猴子尖饭甑尖",
    province: "安徽省",
    city: "宣城市",
    district: "绩溪县",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "奇松怪石。",
    altitude: 900.0,
  },
  {
    id: 39,
    name: "大罗山",
    province: "浙江省",
    city: "温州市",
    district: "龙湾区",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰。线路众多。",
    altitude: 706.9,
  },
  {
    id: 40,
    name: "大明山后山环线",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "注意安全，要攀爬。",
    altitude: 1500.0,
  },
  {
    id: 41,
    name: "风浙线",
    province: "浙江省",
    city: "杭州市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "虐线。",
    altitude: null,
  },
  {
    id: 42,
    name: "浮盖山",
    province: "浙江省",
    city: "衢州市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景较好。",
    altitude: 1146.4,
  },
  {
    id: 43,
    name: "覆卮山",
    province: "浙江省",
    city: "绍兴市",
    district: "上虞区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰。油菜花海。",
    altitude: 861.3,
  },
  {
    id: 44,
    name: "横坑瀑布群",
    province: "浙江省",
    city: "杭州市",
    district: "富阳区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "瀑布多。",
    altitude: null,
  },
  {
    id: 45,
    name: "蝴蝶谷",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "夏日溯溪线",
    altitude: null,
  },
  {
    id: 46,
    name: "黄山168全线",
    province: "安徽省",
    city: "黄山市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "越野线路。",
    altitude: null,
  },
  {
    id: 47,
    name: "尖山五峰",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "攀爬石头，部分路段手脚并用，需绳索。",
    altitude: null,
  },
  {
    id: 48,
    name: "江郎山",
    province: "浙江省",
    city: "衢州市",
    district: "江山市",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "世界自然遗产。",
    altitude: null,
  },
  {
    id: 49,
    name: "仙都山脊环线",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "孤峰耸立。",
    altitude: null,
  },
  {
    id: 50,
    name: "井空里",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "溯溪",
    altitude: null,
  },
  {
    id: 51,
    name: "马岭古道美女峰(一峰九崖)",
    province: "浙江省",
    city: "金华市",
    district: "浦江县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "美女峰海拔905米,为浙中著名奇石.",
    altitude: 905.0,
  },
  {
    id: 52,
    name: "米筛浪",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "临海市与仙居县界山、括苍山脉次高峰、台州市最高峰",
    altitude: 1382.4,
  },
  {
    id: 53,
    name: "磨心尖白石尖环线",
    province: "浙江省",
    city: "杭州市",
    district: "淳安县",
    overall: 4,
    scenery: 3,
    difficulty: 5,
    days: 1,
    backpack: "轻装",
    description: "难度较大，下雨天不要去。",
    altitude: 1523.0,
  },
  {
    id: 54,
    name: "南黄古道",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "摄影，秋色，柿子",
    altitude: null,
  },
  {
    id: 55,
    name: "南麂岛",
    province: "浙江省",
    city: "温州市",
    district: "平阳县",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "国家级自然保护区，海水较为干净。",
    altitude: null,
  },
  {
    id: 56,
    name: "东极岛",
    province: "浙江省",
    city: "舟山市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 1,
    days: 1,
    backpack: "轻装",
    description: "休闲线路。",
    altitude: null,
  },
  {
    id: 57,
    name: "琼台仙谷",
    province: "浙江省",
    city: "台州市",
    district: "天台县",
    overall: 4,
    scenery: 5,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "风景不错，逛风景区。",
    altitude: null,
  },
  {
    id: 58,
    name: "箬竂岘",
    province: "浙江省",
    city: "丽水市",
    district: "松阳县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "松阳县、仙霞岭山脉主峰、松阳县最高峰",
    altitude: 1502.3,
  },
  {
    id: 59,
    name: "水门尖豹C线",
    province: "浙江省",
    city: "衢州市",
    district: "",
    overall: 4,
    scenery: 3,
    difficulty: 5,
    days: 1,
    backpack: "轻装",
    description: "难度较大。注意安全。",
    altitude: 1452.6,
  },
  {
    id: 60,
    name: "四明山",
    province: "浙江省",
    city: "宁波市",
    district: "余姚市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "多条线路。",
    altitude: null,
  },
  {
    id: 61,
    name: "泰山老驴线",
    province: "山东省",
    city: "泰安市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "泰山日出。世界遗产。",
    altitude: null,
  },
  {
    id: 62,
    name: "皖南318（自驾线路）",
    province: "安徽省",
    city: "宣城市",
    district: "宁国市",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "“皖南金项链”，秋色，沿途经皖南主要旅游点及西递宏村等。",
    altitude: null,
  },
  {
    id: 63,
    name: "小黄山",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景秀丽。",
    altitude: null,
  },
  {
    id: 64,
    name: "雁荡四尖穿越",
    province: "浙江省",
    city: "温州市",
    district: "乐清市",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description:
      "雁荡四尖是指雁湖尖、凌云尖、百岗尖、乌岩尖。百岗尖为乐清市、北雁荡山主峰、乐清市最高峰",
    altitude: 1150.0,
  },
  {
    id: 65,
    name: "白云尖",
    province: "浙江省",
    city: "温州市",
    district: "泰顺县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "泰顺县与景宁县界山、洞宫山脉主峰、温州市最高峰",
    altitude: 1611.3,
  },
  {
    id: 66,
    name: "昌北古道（百丈岭古道）",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "三尖线路相关。",
    altitude: null,
  },
  {
    id: 67,
    name: "敕木山",
    province: "甘肃省",
    city: "庆阳市",
    district: "景宁县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "洞宫山脉主峰",
    altitude: 1519.0,
  },
  {
    id: 68,
    name: "船坞山",
    province: "浙江省",
    city: "杭州市",
    district: "萧山区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 744.0,
  },
  {
    id: 69,
    name: "大慈岩",
    province: "浙江省",
    city: "杭州市",
    district: "建德市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，逛大慈岩风景区",
    altitude: null,
  },
  {
    id: 70,
    name: "大寒尖",
    province: "浙江省",
    city: "金华市",
    district: "义乌市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 925.6,
  },
  {
    id: 71,
    name: "大雷山",
    province: "浙江省",
    city: "台州市",
    district: "天台县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "天台县与临海市界山、大盘山脉支脉主峰、天台县最高峰",
    altitude: 1229.4,
  },
  {
    id: 72,
    name: "大盘尖",
    province: "浙江省",
    city: "金华市",
    district: "兰溪市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "兰溪市与婺城区界山、龙门山脉支脉金华山主峰、兰溪市最高峰",
    altitude: 1312.0,
  },
  {
    id: 73,
    name: "大盘山",
    province: "浙江省",
    city: "金华市",
    district: "磐安县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "大盘山脉次高峰",
    altitude: 1274.0,
  },
  {
    id: 74,
    name: "大青冈",
    province: "浙江省",
    city: "温州市",
    district: "永嘉县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "永嘉县、括苍山脉主峰、永嘉县最高峰",
    altitude: 1272.4,
  },
  {
    id: 75,
    name: "大寺基尖",
    province: "浙江省",
    city: "台州市",
    district: "黄岩区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "黄岩区与永嘉县界山、括苍山脉主峰、黄岩区最高峰",
    altitude: 1252.5,
  },
  {
    id: 76,
    name: "东搬山",
    province: "浙江省",
    city: "宁波市",
    district: "象山县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 810.8,
  },
  {
    id: 77,
    name: "东阳马1马2",
    province: "浙江省",
    city: "金华市",
    district: "东阳市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 78,
    name: "洞坑、陶坑",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 79,
    name: "斗岩",
    province: "浙江省",
    city: "绍兴市",
    district: "诸暨市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "部分路段较为陡峭危险，逃票进斗岩风景区",
    altitude: null,
  },
  {
    id: 80,
    name: "飞鹰道划岩山",
    province: "浙江省",
    city: "台州市",
    district: "黄岩区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 81,
    name: "葛岭仙境",
    province: "浙江省",
    city: "湖州市",
    district: "德清县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 82,
    name: "关岛尖",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "缙云县、大盘山脉主峰",
    altitude: 1231.5,
  },
  {
    id: 83,
    name: "观音尖",
    province: "浙江省",
    city: "杭州市",
    district: "桐庐县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "桐庐县、龙门山脉主峰、桐庐县最高峰",
    altitude: 1246.5,
  },
  {
    id: 84,
    name: "华顶峰",
    province: "浙江省",
    city: "台州市",
    district: "天台县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "天台山脉次高峰",
    altitude: 1098.0,
  },
  {
    id: 85,
    name: "纪龙山",
    province: "浙江省",
    city: "杭州市",
    district: "桐庐县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "趣味性，体验项目丰富，可速降探洞及豹子崖崖壁绳降",
    altitude: 467.0,
  },
  {
    id: 86,
    name: "十字峡谷",
    province: "浙江省",
    city: "杭州市",
    district: "桐庐县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 87,
    name: "巾子峰",
    province: "浙江省",
    city: "丽水市",
    district: "庆元县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "洞宫山脉主峰",
    altitude: 1563.2,
  },
  {
    id: 88,
    name: "金鸡山",
    province: "浙江省",
    city: "温州市",
    district: "瑞安市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "瑞安市与青田界山、雁荡山脉最高峰、瑞安市最高峰",
    altitude: 1320.7,
  },
  {
    id: 89,
    name: "金钟峰",
    province: "浙江省",
    city: "绍兴市",
    district: "嵊州市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "嵊州市、四明山脉名义最高峰",
    altitude: 1018.0,
  },
  {
    id: 90,
    name: "蛟坑线",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 91,
    name: "九龙洞ab线",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 92,
    name: "九溪十八涧",
    province: "浙江省",
    city: "杭州市",
    district: "西湖区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "注意限行，停车麻烦",
    altitude: null,
  },
  {
    id: 93,
    name: "括苍古道",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 94,
    name: "括苍山",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 95,
    name: "雷公尖",
    province: "浙江省",
    city: "台州市",
    district: "路桥区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 352.0,
  },
  {
    id: 96,
    name: "柳溪江三尖",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "和尚坪扁担山留尖山",
    altitude: null,
  },
  {
    id: 97,
    name: "六春湖",
    province: "浙江省",
    city: "衢州市",
    district: "龙游县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "龙游县与衢江区界山、仙霞岭山脉主峰、衢州名山",
    altitude: 1390.5,
  },
  {
    id: 98,
    name: "南车悬瀑龙王八潭",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 99,
    name: "南屿古道",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "12公里。风景不错，奇石",
    altitude: 683.0,
  },
  {
    id: 100,
    name: "南园尖",
    province: "浙江省",
    city: "绍兴市",
    district: "诸暨市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "会稽山脉第三高峰、诸暨市最高峰",
    altitude: 1095.0,
  },
  {
    id: 101,
    name: "南正尖",
    province: "浙江省",
    city: "温州市",
    district: "永嘉县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "永括苍山脉主峰、传说为孙悟空诞生地",
    altitude: 1246.0,
  },
  {
    id: 102,
    name: "宁海百里",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 103,
    name: "宁海森林温泉防火道",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 104,
    name: "牛头山",
    province: "浙江省",
    city: "金华市",
    district: "武义县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "武义县与遂昌县界山、仙霞岭山脉主峰、金华市最高峰",
    altitude: 1560.2,
  },
  {
    id: 105,
    name: "菩提峰",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 996.0,
  },
  {
    id: 106,
    name: "菩提岭风车古道",
    province: "浙江省",
    city: "宁波市",
    district: "鄞州区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 107,
    name: "薄刀岩",
    province: "浙江省",
    city: "金华市",
    district: "浦江县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 108,
    name: "齐云山",
    province: "安徽省",
    city: "黄山市",
    district: "休宁县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "道教名山，油菜花或皖南秋色去为宜，同属皖南318。",
    altitude: null,
  },
  {
    id: 109,
    name: "崎云山",
    province: "浙江省",
    city: "丽水市",
    district: "青田县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "青田县与瑞安界山、西雁荡山主峰",
    altitude: 1164.8,
  },
  {
    id: 110,
    name: "棋盘山",
    province: "浙江省",
    city: "温州市",
    district: "平阳县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "平阳县与苍南界山、南雁荡山主峰、平阳县最高峰",
    altitude: 1231.0,
  },
  {
    id: 111,
    name: "青梅尖",
    province: "浙江省",
    city: "金华市",
    district: "磐安县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "大盘山脉最高峰",
    altitude: 1314.0,
  },
  {
    id: 112,
    name: "清水溪、混水溪",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 113,
    name: "香炉尖",
    province: "浙江省",
    city: "丽水市",
    district: "庆元县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 114,
    name: "上山头",
    province: "甘肃省",
    city: "庆阳市",
    district: "景宁县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 115,
    name: "神仙居野线",
    province: "浙江省",
    city: "台州市",
    district: "仙居县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 116,
    name: "十八潭(溯溪)",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 117,
    name: "双苗尖",
    province: "浙江省",
    city: "丽水市",
    district: "庆元县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "庆元县与寿宁县界山、洞宫山脉主峰",
    altitude: 1626.0,
  },
  {
    id: 118,
    name: "桃源尖",
    province: "浙江省",
    city: "衢州市",
    district: "衢江区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "遂昌与衢江龙游界山、仙霞岭山脉主峰、户外网红打卡地",
    altitude: 1438.0,
  },
  {
    id: 119,
    name: "徐霞客古道",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "“浙东唐诗之路”，天台县路段可过铜壶滴漏及石梁飞瀑景区。",
    altitude: null,
  },
  {
    id: 120,
    name: "铁匠山黑洞瀑布群",
    province: "安徽省",
    city: "宣城市",
    district: "宁国市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 121,
    name: "黄金海岸线",
    province: "浙江省",
    city: "台州市",
    district: "温岭市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 122,
    name: "五龙潭环线",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，有山有水，要钻小段灌木林。",
    altitude: null,
  },
  {
    id: 123,
    name: "西白山",
    province: "浙江省",
    city: "绍兴市",
    district: "嵊州市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "嵊州市、会稽山脉次高峰、绍兴市最高峰",
    altitude: 1095.7,
  },
  {
    id: 124,
    name: "西九(西柳岙→九龙湖) 55km",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 125,
    name: "仙都",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 126,
    name: "仙缙古道",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 127,
    name: "白刀岩饭甄岩环线",
    province: "浙江省",
    city: "台州市",
    district: "仙居县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 128,
    name: "仙人谷溯溪",
    province: "浙江省",
    city: "台州市",
    district: "仙居县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 129,
    name: "仙霞古道",
    province: "浙江省",
    city: "衢州市",
    district: "江山市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 130,
    name: "穿岩十九峰",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 131,
    name: "杏梅尖",
    province: "浙江省",
    city: "杭州市",
    district: "富阳区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 132,
    name: "盐帮古道",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description:
      "推荐杨梅成熟季节去，上山沿途可摘杨梅，下山过莒溪十八渡，可玩水",
    altitude: null,
  },
  {
    id: 133,
    name: "新三尖",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "阳山尖，油烧尖，螺蛳尖",
    altitude: null,
  },
  {
    id: 134,
    name: "新四军",
    province: "江苏省",
    city: "无锡市",
    district: "宜兴市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 135,
    name: "八岭坑",
    province: "浙江省",
    city: "金华市",
    district: "义乌市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 136,
    name: "松瀑山",
    province: "浙江省",
    city: "金华市",
    district: "义乌市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 137,
    name: "隐龙山",
    province: "浙江省",
    city: "台州市",
    district: "三门县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 138,
    name: "五指岩",
    province: "浙江省",
    city: "金华市",
    district: "永康市",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "手脚并用+部分路段需借助绳索，山脊线",
    altitude: 719.0,
  },
  {
    id: 139,
    name: "章里高山（黄金山）",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "夏季赏瀑布，冬季赏雪景，部分路段较陡，强度较大",
    altitude: null,
  },
  {
    id: 140,
    name: "浙东大峡谷",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 141,
    name: "指南村",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "看秋景，可徒步上山也可选择景交",
    altitude: null,
  },
  {
    id: 142,
    name: "南尖岩",
    province: "浙江省",
    city: "丽水市",
    district: "遂昌县",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 143,
    name: "大别山三尖",
    province: "安徽省",
    city: "六安市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 2,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 144,
    name: "大别山二号线",
    province: "安徽省",
    city: "六安市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "轻装",
    description: "瀑布完全线",
    altitude: null,
  },
  {
    id: 145,
    name: "西湖群山毅行",
    province: "浙江省",
    city: "杭州市",
    district: "西湖区",
    overall: 3,
    scenery: 3,
    difficulty: 4,
    days: 1,
    backpack: "轻装",
    description: "自虐练腿。",
    altitude: null,
  },
  {
    id: 146,
    name: "三岗二尖",
    province: "浙江省",
    city: "绍兴市",
    district: "柯桥区",
    overall: 3,
    scenery: 3,
    difficulty: 4,
    days: 1,
    backpack: "轻装",
    description: "(埃码尖，栗子岗，龙潭岗，望海岗，诸葛尖)",
    altitude: null,
  },
  {
    id: 147,
    name: "灵山29峰",
    province: "江西省",
    city: "上饶市",
    district: "",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 148,
    name: "灵树/灵白/吴中十峰",
    province: "江苏省",
    city: "苏州市",
    district: "",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 149,
    name: "龙门岗",
    province: "浙江省",
    city: "衢州市",
    district: "江山市",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "仙霞岭山脉主峰、衢州市次高峰",
    altitude: 1454.5,
  },
  {
    id: 150,
    name: "鸬鸟山",
    province: "浙江省",
    city: "杭州市",
    district: "余杭区",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 151,
    name: "老山东西线",
    province: "江苏省",
    city: "南京市",
    district: "",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 152,
    name: "八面湖",
    province: "浙江省",
    city: "丽水市",
    district: "青田县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "莲都区与青田县界山、洞宫山脉主峰、两地最高峰",
    altitude: 1390.8,
  },
  {
    id: 153,
    name: "白菊花尖",
    province: "浙江省",
    city: "衢州市",
    district: "常山县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "常山县与柯城区界山、千里岗山脉主峰、两地最高峰",
    altitude: 1394.7,
  },
  {
    id: 154,
    name: "白马山",
    province: "浙江省",
    city: "丽水市",
    district: "遂昌县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "仙霞岭山脉主峰",
    altitude: 1621.0,
  },
  {
    id: 155,
    name: "白石尖",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "开化县、千里岗山脉主峰、开化最高峰",
    altitude: 1453.7,
  },
  {
    id: 156,
    name: "荸荠嶂",
    province: "浙江省",
    city: "温州市",
    district: "瓯海区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "瓯海与青田瑞安界山、西雁荡山主峰、瓯海区最高峰",
    altitude: 1052.0,
  },
  {
    id: 157,
    name: "笔架山三渡溪",
    province: "浙江省",
    city: "金华市",
    district: "永康市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 158,
    name: "苍山",
    province: "浙江省",
    city: "台州市",
    district: "天台县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "天台山脉最高峰",
    altitude: 1113.4,
  },
  {
    id: 159,
    name: "朝天门",
    province: "浙江省",
    city: "金华市",
    district: "浦江县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "龙门山脉主峰、浦江县最高峰",
    altitude: 1050.0,
  },
  {
    id: 160,
    name: "大雷山稻香谷环线",
    province: "浙江省",
    city: "宁波市",
    district: "奉化区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 161,
    name: "大龙岗",
    province: "浙江省",
    city: "衢州市",
    district: "江山市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "江山市、仙霞岭山脉主峰、衢州市最高峰",
    altitude: 1500.3,
  },
  {
    id: 162,
    name: "豆腐皮古道",
    province: "浙江省",
    city: "杭州市",
    district: "富阳区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 163,
    name: "古田山",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 164,
    name: "官坑古道",
    province: "江西省",
    city: "上饶市",
    district: "婺源县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 165,
    name: "光福七尖",
    province: "江苏省",
    city: "苏州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 166,
    name: "韩妃江",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 167,
    name: "黄杨尖",
    province: "浙江省",
    city: "舟山市",
    district: "定海区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 503.6,
  },
  {
    id: 168,
    name: "径山古道",
    province: "浙江省",
    city: "杭州市",
    district: "余杭区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "主要参观径山寺庙",
    altitude: null,
  },
  {
    id: 169,
    name: "九峰尖",
    province: "浙江省",
    city: "温州市",
    district: "苍南县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "苍南县与泰顺界山、南雁荡山最高峰、苍南县最高峰",
    altitude: 1237.3,
  },
  {
    id: 170,
    name: "军障古道",
    province: "江苏省",
    city: "无锡市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 171,
    name: "砍柴岙",
    province: "浙江省",
    city: "宁波市",
    district: "鄞州区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 172,
    name: "栲栳古道",
    province: "浙江省",
    city: "宁波市",
    district: "慈溪市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，附近有鸣鹤古镇，多条经典轨迹，路过杨梅林",
    altitude: null,
  },
  {
    id: 173,
    name: "刻石山",
    province: "浙江省",
    city: "绍兴市",
    district: "柯桥区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 763.8,
  },
  {
    id: 174,
    name: "龙娘山",
    province: "浙江省",
    city: "温州市",
    district: "鹿城区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 858.0,
  },
  {
    id: 175,
    name: "螺蛳尖",
    province: "浙江省",
    city: "金华市",
    district: "金东区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 890.0,
  },
  {
    id: 176,
    name: "前坑顶",
    province: "浙江省",
    city: "舟山市",
    district: "嵊泗县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 236.9,
  },
  {
    id: 177,
    name: "乾隆古道乌石古道",
    province: "江苏省",
    city: "无锡市",
    district: "宜兴市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景一般",
    altitude: null,
  },
  {
    id: 178,
    name: "荞麦岭古道",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "要钻小段灌木林",
    altitude: null,
  },
  {
    id: 179,
    name: "三洲古道",
    province: "江苏省",
    city: "无锡市",
    district: "宜兴市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景一般",
    altitude: null,
  },
  {
    id: 180,
    name: "萝岩山",
    province: "浙江省",
    city: "绍兴市",
    district: "上虞区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "刀脊，需要一定技巧，有大环线小环线，起终点为上虞杨梅林",
    altitude: 400.0,
  },
  {
    id: 181,
    name: "十八重穿越",
    province: "福建省",
    city: "福州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 182,
    name: "石门洞背山脊线",
    province: "浙江省",
    city: "丽水市",
    district: "青田县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 183,
    name: "石牛山",
    province: "浙江省",
    city: "丽水市",
    district: "缙云县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "缙云县、括苍山脉主峰、户外网红打卡地",
    altitude: 1158.0,
  },
  {
    id: 184,
    name: "天字山",
    province: "浙江省",
    city: "湖州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "路过天字禅寺、紫藤林，黄觉禅寺，狮峰禅寺，轨迹较多",
    altitude: null,
  },
  {
    id: 185,
    name: "王位山",
    province: "浙江省",
    city: "湖州市",
    district: "德清县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 186,
    name: "微开古道",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 187,
    name: "萧富古道",
    province: "浙江省",
    city: "杭州市",
    district: "富阳区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 188,
    name: "新安江十里画廊",
    province: "安徽省",
    city: "黄山市",
    district: "歙县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 189,
    name: "休龙古道",
    province: "安徽省",
    city: "黄山市",
    district: "休宁县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 190,
    name: "休婺古道",
    province: "安徽省",
    city: "黄山市",
    district: "休宁县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 191,
    name: "雪窦山",
    province: "浙江省",
    city: "绍兴市",
    district: "柯桥区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，雪窦山风景区",
    altitude: null,
  },
  {
    id: 192,
    name: "杨顶峰",
    province: "浙江省",
    city: "温州市",
    district: "文成县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "文成县、洞宫山脉主峰、文成县最高峰",
    altitude: 1362.0,
  },
  {
    id: 193,
    name: "窑头山",
    province: "浙江省",
    city: "杭州市",
    district: "余杭区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 194,
    name: "一线天锅底山大环线",
    province: "江苏省",
    city: "无锡市",
    district: "宜兴市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 195,
    name: "宜兴龙脊线",
    province: "江苏省",
    city: "无锡市",
    district: "宜兴市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 196,
    name: "鹰嘴岩",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，怪石嶙峋",
    altitude: null,
  },
  {
    id: 197,
    name: "月宫古道",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "粉黛子开放季节首选，花海+古道徒步，金山村",
    altitude: null,
  },
  {
    id: 198,
    name: "小武功山九连尖",
    province: "江苏省",
    city: "镇江市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "强度不大，一日轻装，九尖连穿，风景尚可，高山草甸",
    altitude: null,
  },
  {
    id: 199,
    name: "安顶山",
    province: "浙江省",
    city: "杭州市",
    district: "萧山区",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景一般",
    altitude: null,
  },
  {
    id: 200,
    name: "白云源环线",
    province: "浙江省",
    city: "杭州市",
    district: "桐庐县",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 201,
    name: "大陈岛",
    province: "浙江省",
    city: "台州市",
    district: "椒江区",
    overall: 3,
    scenery: 3,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 202,
    name: "大雷头",
    province: "浙江省",
    city: "台州市",
    district: "玉环市",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 443.0,
  },
  {
    id: 203,
    name: "大鹿岛",
    province: "浙江省",
    city: "台州市",
    district: "玉环市",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 204,
    name: "大宋线路",
    province: "浙江省",
    city: "杭州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，公路较多，线路杂乱，注意限行",
    altitude: null,
  },
  {
    id: 205,
    name: "大蚊虫岛",
    province: "浙江省",
    city: "舟山市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 206,
    name: "大嵛山岛",
    province: "福建省",
    city: "宁德市",
    district: "福鼎市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 207,
    name: "岱山岛",
    province: "浙江省",
    city: "舟山市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 208,
    name: "东甲岛",
    province: "福建省",
    city: "福州市",
    district: "平潭县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 209,
    name: "对峙山",
    province: "上海市",
    city: "上海市",
    district: "普陀区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 544.4,
  },
  {
    id: 210,
    name: "枸杞岛+嵊泗列岛",
    province: "浙江省",
    city: "舟山市",
    district: "嵊泗县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 211,
    name: "桂川古道",
    province: "浙江省",
    city: "温州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 212,
    name: "皇戏梁",
    province: "浙江省",
    city: "台州市",
    district: "三门县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 882.4,
  },
  {
    id: 213,
    name: "黄寮尖",
    province: "浙江省",
    city: "金华市",
    district: "永康市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 930.0,
  },
  {
    id: 214,
    name: "黄泥浆岗",
    province: "浙江省",
    city: "宁波市",
    district: "奉化区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 976.0,
  },
  {
    id: 215,
    name: "黄石山",
    province: "浙江省",
    city: "台州市",
    district: "椒江区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 576.9,
  },
  {
    id: 216,
    name: "黄塔顶",
    province: "浙江省",
    city: "湖州市",
    district: "长兴县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 611.5,
  },
  {
    id: 217,
    name: "徽杭古道",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 218,
    name: "徽青古道",
    province: "安徽省",
    city: "黄山市",
    district: "歙县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 219,
    name: "筋竹古道",
    province: "浙江省",
    city: "温州市",
    district: "乐清市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 220,
    name: "梅田古道",
    province: "浙江省",
    city: "丽水市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 221,
    name: "莫干山，碧坞龙潭",
    province: "浙江省",
    city: "湖州市",
    district: "德清县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "逃票进莫干山，多条经典轨迹",
    altitude: null,
  },
  {
    id: 222,
    name: "莫干山蒋公道",
    province: "浙江省",
    city: "湖州市",
    district: "德清县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 223,
    name: "奶部山",
    province: "浙江省",
    city: "宁波市",
    district: "鄞州区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 915.4,
  },
  {
    id: 224,
    name: "娘娘山(甘岭水库)",
    province: "浙江省",
    city: "杭州市",
    district: "余杭区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 225,
    name: "秦望山",
    province: "浙江省",
    city: "绍兴市",
    district: "越城区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 543.6,
  },
  {
    id: 226,
    name: "青虎湾岗",
    province: "浙江省",
    city: "宁波市",
    district: "余姚市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 979.0,
  },
  {
    id: 227,
    name: "青尖",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "开化县、白际山脉之古田山主峰",
    altitude: 1257.4,
  },
  {
    id: 228,
    name: "湫水山穿越线路",
    province: "浙江省",
    city: "台州市",
    district: "三门县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 229,
    name: "日岭古道",
    province: "浙江省",
    city: "宁波市",
    district: "奉化区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 230,
    name: "如意尖",
    province: "浙江省",
    city: "杭州市",
    district: "西湖区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 536.3,
  },
  {
    id: 231,
    name: "三条岭古道",
    province: "浙江省",
    city: "温州市",
    district: "苍南县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 232,
    name: "山羊坞尖",
    province: "浙江省",
    city: "杭州市",
    district: "建德市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "建德市与淳安县界山、千里岗山脉主峰、建德市最高峰",
    altitude: 1157.8,
  },
  {
    id: 233,
    name: "山阴古道",
    province: "浙江省",
    city: "绍兴市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，一路溪水相随，爬台阶进叶家山古村落",
    altitude: null,
  },
  {
    id: 234,
    name: "上堡山",
    province: "浙江省",
    city: "台州市",
    district: "温岭市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 235,
    name: "上青古道",
    province: "浙江省",
    city: "绍兴市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 236,
    name: "十里银杏",
    province: "浙江省",
    city: "湖州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 237,
    name: "孙家岭古道",
    province: "浙江省",
    city: "绍兴市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错",
    altitude: null,
  },
  {
    id: 238,
    name: "塔川宏村",
    province: "安徽省",
    city: "黄山市",
    district: "黟县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 239,
    name: "蹋脑岗",
    province: "浙江省",
    city: "宁波市",
    district: "慈溪市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 446.0,
  },
  {
    id: 240,
    name: "太白山",
    province: "浙江省",
    city: "宁波市",
    district: "北仑区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 653.3,
  },
  {
    id: 241,
    name: "太湖尖",
    province: "浙江省",
    city: "台州市",
    district: "温岭市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 733.9,
  },
  {
    id: 242,
    name: "太华山",
    province: "江苏省",
    city: "无锡市",
    district: "宜兴市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 243,
    name: "桃花岭",
    province: "浙江省",
    city: "宁波市",
    district: "慈溪市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，强度不大",
    altitude: null,
  },
  {
    id: 244,
    name: "天荒坪",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "雪景不错，多条经典线路。",
    altitude: null,
  },
  {
    id: 245,
    name: "天姥山",
    province: "浙江省",
    city: "绍兴市",
    district: "新昌县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 246,
    name: "天龙古道",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description:
      "路线是由安吉长潭村后开始徒步，经桐杭岗、千亩田、龙王山、天龙古道、仙人顶，至西天目，全程20公里。",
    altitude: null,
  },
  {
    id: 247,
    name: "嶀山古道",
    province: "浙江省",
    city: "绍兴市",
    district: "嵊州市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 248,
    name: "外溪岗",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "开化县与休宁县界山、白际山脉西南段最高峰",
    altitude: 1266.8,
  },
  {
    id: 249,
    name: "文成古道",
    province: "浙江省",
    city: "温州市",
    district: "文成县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 250,
    name: "乌龙古道",
    province: "浙江省",
    city: "湖州市",
    district: "长兴县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，路过乌龙庙、振天寺，要钻小段灌木林，有多条线路",
    altitude: null,
  },
  {
    id: 251,
    name: "乌石山",
    province: "浙江省",
    city: "衢州市",
    district: "江山市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 252,
    name: "乾隆古道",
    province: "江苏省",
    city: "无锡市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 253,
    name: "五股尖六股尖穿越",
    province: "江西省",
    city: "上饶市",
    district: "婺源县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 254,
    name: "五指山",
    province: "浙江省",
    city: "湖州市",
    district: "德清县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 745.5,
  },
  {
    id: 255,
    name: "午潮山",
    province: "浙江省",
    city: "杭州市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "轨迹较多",
    altitude: null,
  },
  {
    id: 256,
    name: "西湖顶",
    province: "浙江省",
    city: "湖州市",
    district: "吴兴区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 651.0,
  },
  {
    id: 257,
    name: "栖霞坑古道",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 258,
    name: "香榧古道",
    province: "浙江省",
    city: "绍兴市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 259,
    name: "香炉峰",
    province: "浙江省",
    city: "绍兴市",
    district: "",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，要买门票",
    altitude: null,
  },
  {
    id: 260,
    name: "小金竹尖",
    province: "浙江省",
    city: "金华市",
    district: "婺城区",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "婺城区、仙霞岭山脉主峰、婺城区最高峰",
    altitude: 1336.0,
  },
  {
    id: 261,
    name: "啸天龙",
    province: "浙江省",
    city: "杭州市",
    district: "淳安县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "淳安县与歙县界山、白际山脉主峰",
    altitude: 1395.4,
  },
  {
    id: 262,
    name: "燕窝古道",
    province: "浙江省",
    city: "宁波市",
    district: "余姚市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错",
    altitude: null,
  },
  {
    id: 263,
    name: "羊额古道",
    province: "浙江省",
    city: "宁波市",
    district: "余姚市",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错，要钻小段灌木林",
    altitude: null,
  },
  {
    id: 264,
    name: "永乐古道",
    province: "浙江省",
    city: "温州市",
    district: "永嘉县",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 265,
    name: "百丈平森林古道",
    province: "浙江省",
    city: "杭州市",
    district: "余杭区",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "强度较大，只有起点处2公里风景较好，其余为无风景机耕路",
    altitude: null,
  },
  {
    id: 266,
    name: "弁山",
    province: "浙江省",
    city: "湖州市",
    district: "",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "路过法华寺，8字轨迹，要钻小段灌木林",
    altitude: null,
  },
  {
    id: 267,
    name: "大嵩岭古道",
    province: "浙江省",
    city: "宁波市",
    district: "",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 268,
    name: "东海茶山",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "山上云海不错，从脚缝穿过，越过山脊形成云瀑",
    altitude: null,
  },
  {
    id: 269,
    name: "洞头岛",
    province: "浙江省",
    city: "温州市",
    district: "",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 270,
    name: "都林山环线",
    province: "浙江省",
    city: "杭州市",
    district: "临安区",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "风景一般，机耕路较多",
    altitude: null,
  },
  {
    id: 271,
    name: "独松关",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "路过釜托禅寺，古寺里风景不错",
    altitude: null,
  },
  {
    id: 272,
    name: "杜岙大环线",
    province: "浙江省",
    city: "宁波市",
    district: "慈溪市",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 273,
    name: "高鳌山",
    province: "浙江省",
    city: "舟山市",
    district: "岱山县",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 299.6,
  },
  {
    id: 274,
    name: "高姥山",
    province: "浙江省",
    city: "金华市",
    district: "磐安县",
    overall: 2,
    scenery: 3,
    difficulty: 1,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 275,
    name: "冠佩村",
    province: "浙江省",
    city: "宁波市",
    district: "余姚市",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 276,
    name: "鹤浦岛",
    province: "浙江省",
    city: "宁波市",
    district: "象山县",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 277,
    name: "红树林",
    province: "浙江省",
    city: "台州市",
    district: "临海市",
    overall: 2,
    scenery: 2,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 278,
    name: "花岱岛",
    province: "浙江省",
    city: "宁波市",
    district: "象山县",
    overall: 2,
    scenery: 3,
    difficulty: 1,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 279,
    name: "吉山赏梅",
    province: "浙江省",
    city: "杭州市",
    district: "萧山区",
    overall: 2,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "赏梅",
    altitude: null,
  },
  {
    id: 280,
    name: "驾云山",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 2,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景一般，机耕路较多，路旁杜鹃花多，路过一人工山洞",
    altitude: null,
  },
  {
    id: 281,
    name: "陆羽古道（霞幕山）",
    province: "浙江省",
    city: "湖州市",
    district: "",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "路过云林禅寺，轨迹较多",
    altitude: null,
  },
  {
    id: 282,
    name: "茅山坑",
    province: "浙江省",
    city: "衢州市",
    district: "龙游县",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "龙游县与衢江区界山、仙霞岭山脉主峰、龙游县最高峰",
    altitude: 1442.0,
  },
  {
    id: 283,
    name: "蛇蟠岛",
    province: "浙江省",
    city: "台州市",
    district: "三门县",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 284,
    name: "石耳山",
    province: "浙江省",
    city: "衢州市",
    district: "开化县",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "开化县与婺源县界山、白际山脉主峰",
    altitude: 1260.0,
  },
  {
    id: 285,
    name: "寺坞岭",
    province: "浙江省",
    city: "杭州市",
    district: "萧山区",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 286,
    name: "檀头山岛",
    province: "浙江省",
    city: "宁波市",
    district: "象山县",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 287,
    name: "陶朱山",
    province: "浙江省",
    city: "绍兴市",
    district: "诸暨市",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 288,
    name: "铁瓦寺",
    province: "安徽省",
    city: "宣城市",
    district: "宁国市",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 289,
    name: "蟹背尖",
    province: "浙江省",
    city: "宁波市",
    district: "宁海县",
    overall: 2,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 954.0,
  },
  {
    id: 290,
    name: "赋石水库",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 1,
    scenery: 1,
    difficulty: 1,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 291,
    name: "高阳山",
    province: "浙江省",
    city: "嘉兴市",
    district: "海盐县",
    overall: 1,
    scenery: 2,
    difficulty: 1,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 251.6,
  },
  {
    id: 292,
    name: "红卫水库",
    province: "浙江省",
    city: "湖州市",
    district: "",
    overall: 1,
    scenery: 1,
    difficulty: 1,
    days: 1,
    backpack: "轻装",
    description: "5公里爬山+游泳，野营，野炊",
    altitude: null,
  },
  {
    id: 293,
    name: "神游坞",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 1,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "游泳",
    altitude: null,
  },
  {
    id: 294,
    name: "苕溪北湖草荡",
    province: "浙江省",
    city: "杭州市",
    district: "余杭区",
    overall: 1,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 295,
    name: "五百岗环线",
    province: "浙江省",
    city: "绍兴市",
    district: "",
    overall: 1,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景一般，公里较多",
    altitude: null,
  },
  {
    id: 296,
    name: "下孤城遗址",
    province: "浙江省",
    city: "湖州市",
    district: "",
    overall: 1,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "公路较多",
    altitude: null,
  },
  {
    id: 297,
    name: "丫髻山",
    province: "浙江省",
    city: "台州市",
    district: "玉环市",
    overall: 1,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 298,
    name: "烟墩山",
    province: "浙江省",
    city: "温州市",
    district: "洞头县",
    overall: 1,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "所在区县最高峰",
    altitude: 391.8,
  },
  {
    id: 299,
    name: "渔山列岛",
    province: "浙江省",
    city: "宁波市",
    district: "象山县",
    overall: 1,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 300,
    name: "云台山",
    province: "浙江省",
    city: "杭州市",
    district: "富阳区",
    overall: 1,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 301,
    name: "浙西大草原",
    province: "浙江省",
    city: "衢州市",
    district: "衢江区",
    overall: 1,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 302,
    name: "大别山三尖",
    province: "安徽省",
    city: "六安市",
    district: "",
    overall: 4,
    scenery: 4,
    difficulty: 3,
    days: 2,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 303,
    name: "大别山二号线",
    province: "安徽省",
    city: "六安市",
    district: "",
    overall: 4,
    scenery: 5,
    difficulty: 3,
    days: 2,
    backpack: "轻装",
    description: "瀑布完全线",
    altitude: null,
  },
  {
    id: 304,
    name: "丫髻山",
    province: "江苏省",
    city: "",
    district: "溧阳",
    overall: 1,
    scenery: 3,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 305,
    name: "仙山头",
    province: "江苏省",
    city: "",
    district: "溧阳",
    overall: 3,
    scenery: 4,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "风景不错",
    altitude: null,
  },
  {
    id: 306,
    name: "茅山",
    province: "江苏省",
    city: "",
    district: "金坛",
    overall: 2,
    scenery: 3,
    difficulty: 2,
    days: 1,
    backpack: "轻装",
    description: "",
    altitude: null,
  },
  {
    id: 307,
    name: "南天目红石崖",
    province: "浙江省",
    city: "湖州市",
    district: "安吉县",
    overall: 3,
    scenery: 3,
    difficulty: 3,
    days: 1,
    backpack: "轻装",
    description: "全程约10.63公里，最高海拔累计爬升821米。",
    altitude: null,
  },
];

const RouteCard = ({ route }: { route: Route }) => {
  const renderStars = (count: number) => {
    return Array(count)
      .fill(0)
      .map((_, index) => (
        <Star key={index} className="w-4 h-4 text-yellow-400 fill-yellow-400" />
      ));
  };

  return (
    <Dialog>
      <DialogTrigger className="w-full p-4">
        <Card className="group relative overflow-hidden rounded-lg h-80">
          {/* 使用占位图片 */}
          <img
            src={`/api/placeholder/600/800`}
            alt={route.name}
            className="w-full h-full object-cover transition-transform group-hover:scale-105"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/40 to-transparent p-4 flex flex-col justify-end">
            <h3 className="text-xl font-bold text-white mb-2">{route.name}</h3>
            <div className="flex items-center gap-2 text-white mb-1">
              <span>难度：</span>
              <div className="flex">{renderStars(route.difficulty)}</div>
            </div>

            <div className="flex items-center gap-2 text-white mt-1">
              <span>风景：</span>
              <div className="flex">{renderStars(route.scenery)}</div>
            </div>
            <div className="flex items-center gap-2 text-white mt-1">
              <span>海拔：</span>
              <p className="text-white">海拔：{route.altitude}米</p>
            </div>
          </div>
        </Card>
      </DialogTrigger>

      <DialogContent className="max-w-[90vw] md:max-w-md rounded-lg">
        <DialogHeader>
          <DialogTitle>{route.name}</DialogTitle>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid grid-cols-2 gap-2">
            <div className="font-semibold">位置</div>
            <div>{`${route.province}${route.city}${route.district}`}</div>

            <div className="font-semibold">综合评分</div>
            <div className="flex">{renderStars(route.overall)}</div>

            <div className="font-semibold">风景评分</div>
            <div className="flex">{renderStars(route.scenery)}</div>

            <div className="font-semibold">难度</div>
            <div className="flex">{renderStars(route.difficulty)}</div>

            <div className="font-semibold">所需天数</div>
            <div>{route.days}天</div>

            <div className="font-semibold">背负类型</div>
            <div>{route.backpack}</div>

            <div className="font-semibold">海拔</div>
            <div>{route.altitude}米</div>
          </div>

          <div>
            <div className="font-semibold mb-2">线路简介</div>
            <p className="text-sm text-gray-600">{route.description}</p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
};

const FilterBar = ({
  filters,
  setFilters,
}: {
  filters: Filters;
  setFilters: Dispatch<SetStateAction<Filters>>;
}) => {
  return (
    <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
      <div className="relative">
        <Search className="absolute left-2 top-2.5 h-4 w-4 text-gray-500" />
        <Input
          placeholder="搜索路线名称..."
          className="pl-8"
          value={filters.search}
          onChange={(e) =>
            setFilters((prev: Filters) => ({ ...prev, search: e.target.value }))
          }
        />
      </div>

      <Select
        value={String(filters.scenery)}
        onValueChange={(value) =>
          setFilters((prev: Filters) => ({ ...prev, scenery: Number(value) }))
        }
      >
        <SelectTrigger>
          <SelectValue placeholder="风景评分" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="0">全部风景</SelectItem>
          {[5, 4, 3, 2, 1].map((value) => (
            <SelectItem key={value} value={String(value)}>
              {value} 星
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      <Select
        value={String(filters.difficulty)}
        onValueChange={(value) =>
          setFilters((prev) => ({ ...prev, difficulty: Number(value) }))
        }
      >
        <SelectTrigger>
          <SelectValue placeholder="难度" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="0">全部难度</SelectItem>
          {[5, 4, 3, 2, 1].map((value) => (
            <SelectItem key={value} value={String(value)}>
              {value} 星
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      <Select
        value={String(filters.days)}
        onValueChange={(value) =>
          setFilters((prev: Filters) => ({ ...prev, days: Number(value) }))
        }
      >
        <SelectTrigger>
          <SelectValue placeholder="所需天数" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="0">全部天数</SelectItem>
          {[1, 2, 3, 4, 5].map((value) => (
            <SelectItem key={value} value={String(value)}>
              {value} 天
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      <Select
        value={filters.backpack}
        onValueChange={(value) =>
          setFilters((prev: Filters) => ({ ...prev, backpack: value }))
        }
      >
        <SelectTrigger>
          <SelectValue placeholder="背负类型" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="全部类型">全部类型</SelectItem>
          <SelectItem value="重装">重装</SelectItem>
          <SelectItem value="轻装">轻装</SelectItem>
        </SelectContent>
      </Select>
    </div>
  );
};

const HikingRoutes = () => {
  const [filters, setFilters] = useState({
    search: "",
    scenery: 0,
    difficulty: 0,
    days: 0,
    backpack: "全部类型",
  });

  const filteredRoutes = useMemo(() => {
    return routes.filter((route) => {
      // 搜索名称
      if (
        filters.search &&
        !route.name.toLowerCase().includes(filters.search.toLowerCase())
      ) {
        return false;
      }
      // 风景评分
      if (filters.scenery > 0 && route.scenery !== filters.scenery) {
        return false;
      }
      // 难度
      if (filters.difficulty > 0 && route.difficulty !== filters.difficulty) {
        return false;
      }
      // 天数
      if (filters.days > 0 && route.days !== filters.days) {
        return false;
      }
      // 背负类型
      if (
        filters.backpack != "全部类型" &&
        route.backpack !== filters.backpack
      ) {
        return false;
      }
      return true;
    });
  }, [filters]);

  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-2xl font-bold mb-6">徒步路线推荐</h1>

      <FilterBar filters={filters} setFilters={setFilters} />

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {filteredRoutes.map((route) => (
          <RouteCard key={route.id} route={route} />
        ))}
      </div>

      {filteredRoutes.length === 0 && (
        <div className="text-center py-8 text-gray-500">
          没有找到符合条件的路线
        </div>
      )}
    </div>
  );
};

export default HikingRoutes;
